language: csharp
sudo: false
mono:
  - latest
  - 4.2.1
  - 3.2.8
  - 4.2.1
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      mono: 3.2.8
  allow_failures:
    - mono: latest
  fast_finish: true
script:
  - ./build.sh --target "Travis"
